import type { LegalTask } from "./task-types";

/** Canonical 14 tasks for development / fallback when GET /api/legal/tasks is unavailable. */
export const TASK_FIXTURES: LegalTask[] = [
  {
    task_id: "review_contract",
    display_name_es: "Revisar contrato",
    display_name_en: "Review contract",
    description_es: "Análisis de riesgos y cláusulas en un contrato cargado",
    description_en: "Risk and clause analysis on an uploaded contract",
    section_es: "Contratos",
    section_en: "Contracts",
    icon_hint: "file-search",
    agent_chain: ["document_classifier", "contract_analyzer", "analizador_riesgo_contractual"],
    default_practice_area_tags: ["civil", "bancario"],
    required_inputs: [
      { field: "document_file", type: "file", formats: ["pdf"], max_size_mb: 20, required: true, label_es: "Documento PDF" },
    ],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 8000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: ["contract_review"],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 30 segundos",
    estimated_time_en: "≈ 30 seconds",
  },
  {
    task_id: "clause_risk_scan",
    display_name_es: "Escanear cláusulas de riesgo",
    display_name_en: "Clause risk scan",
    description_es: "Detección de patrones abusivos o desproporcionados",
    description_en: "Detect abusive or disproportionate patterns",
    section_es: "Contratos",
    section_en: "Contracts",
    icon_hint: "alert-triangle",
    agent_chain: ["analizador_riesgo_contractual"],
    default_practice_area_tags: ["civil", "mercantil"],
    required_inputs: [{ field: "contract_text", type: "textarea", required: true, label_es: "Texto del contrato" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 6000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 20 segundos",
    estimated_time_en: "≈ 20 seconds",
  },
  {
    task_id: "nda_review",
    display_name_es: "Revisar confidencialidad (NDA)",
    display_name_en: "NDA review",
    description_es: "Alcance, duración y excepciones del acuerdo",
    description_en: "Scope, term and exceptions",
    section_es: "Contratos",
    section_en: "Contracts",
    icon_hint: "shield",
    agent_chain: ["redactor_contratos"],
    default_practice_area_tags: ["mercantil"],
    required_inputs: [{ field: "nda_text", type: "textarea", required: true, label_es: "Texto del NDA" }],
    output_type: "navigate",
    navigate_path: "/legal/contracts?task=nda_review",
    requires_attorney_review: true,
    max_execution_time_ms: 5000,
    risk_level: "low",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 25 segundos",
    estimated_time_en: "≈ 25 seconds",
  },
  {
    task_id: "loan_agreement_review",
    display_name_es: "Revisar contrato de préstamo",
    display_name_en: "Loan agreement review",
    description_es: "Cláusulas financieras y protección al consumidor",
    description_en: "Financial clauses and consumer protection",
    section_es: "Contratos",
    section_en: "Contracts",
    icon_hint: "landmark",
    agent_chain: ["analizador_riesgo_contractual"],
    default_practice_area_tags: ["bancario", "civil"],
    required_inputs: [{ field: "contract_text", type: "textarea", required: true, label_es: "Contrato" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 7000,
    risk_level: "high",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 45 segundos",
    estimated_time_en: "≈ 45 seconds",
  },
  {
    task_id: "guaranty_review",
    display_name_es: "Revisar garantías y avales",
    display_name_en: "Guaranty review",
    description_es: "Obligaciones solidarias y límites legales",
    description_en: "Joint obligations and legal limits",
    section_es: "Contratos",
    section_en: "Contracts",
    icon_hint: "file-badge",
    agent_chain: ["redactor_contratos"],
    default_practice_area_tags: ["bancario"],
    required_inputs: [{ field: "guaranty_text", type: "textarea", required: true, label_es: "Documento de garantía" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 6000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 35 segundos",
    estimated_time_en: "≈ 35 seconds",
  },
  {
    task_id: "timeline_builder",
    display_name_es: "Construir línea de tiempo del caso",
    display_name_en: "Case timeline",
    description_es: "Hechos y hitos procesales ordenados",
    description_en: "Ordered facts and procedural milestones",
    section_es: "Litigios",
    section_en: "Litigation",
    icon_hint: "git-branch",
    agent_chain: ["verificador_prescripcion"],
    default_practice_area_tags: ["procesal", "civil"],
    required_inputs: [{ field: "hechos", type: "textarea", required: true, label_es: "Hechos relevantes" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 9000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 1 minuto",
    estimated_time_en: "≈ 1 minute",
  },
  {
    task_id: "prescription_check",
    display_name_es: "Verificar prescripción",
    display_name_en: "Prescription check",
    description_es: "Análisis orientativo de caducidad de acciones",
    description_en: "Orientative expiry analysis",
    section_es: "Litigios",
    section_en: "Litigation",
    icon_hint: "clock",
    agent_chain: ["verificador_prescripcion"],
    default_practice_area_tags: ["civil", "procesal"],
    required_inputs: [
      { field: "fecha_hecho", type: "text", required: true, label_es: "Fecha del hecho" },
      { field: "consulta", type: "textarea", required: false, label_es: "Contexto" },
    ],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 5000,
    risk_level: "high",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 25 segundos",
    estimated_time_en: "≈ 25 seconds",
  },
  {
    task_id: "deadlines_calc",
    display_name_es: "Calcular plazos procesales",
    display_name_en: "Procedural deadlines",
    description_es: "Plazos según tipo de notificación y proceso",
    description_en: "Deadlines by notification type",
    section_es: "Litigios",
    section_en: "Litigation",
    icon_hint: "calendar",
    agent_chain: ["calculador_plazos_procesales"],
    default_practice_area_tags: ["procesal"],
    required_inputs: [
      { field: "fecha_notificacion", type: "text", required: true, label_es: "Fecha de notificación" },
      { field: "dias_plazo", type: "text", required: true, label_es: "Días de plazo" },
    ],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 4000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 15 segundos",
    estimated_time_en: "≈ 15 seconds",
  },
  {
    task_id: "filing_checklist",
    display_name_es: "Lista de verificación para demanda",
    display_name_en: "Filing checklist",
    description_es: "Requisitos formales antes de interponer demanda",
    description_en: "Formal requirements before filing",
    section_es: "Litigios",
    section_en: "Litigation",
    icon_hint: "list-checks",
    agent_chain: ["validador_citas_legales"],
    default_practice_area_tags: ["procesal"],
    required_inputs: [{ field: "texto", type: "textarea", required: true, label_es: "Borrador o hechos" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 6000,
    risk_level: "low",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 30 segundos",
    estimated_time_en: "≈ 30 seconds",
  },
  {
    task_id: "aml_kyc_scan",
    display_name_es: "Pantalla rápida AML/KYC",
    display_name_en: "AML/KYC quick screen",
    description_es: "Evaluación heurística con contexto normativo",
    description_en: "Heuristic screening with regulatory context",
    section_es: "Compliance",
    section_en: "Compliance",
    icon_hint: "shield-check",
    agent_chain: ["validador_amlkyc"],
    default_practice_area_tags: ["compliance", "bancario"],
    required_inputs: [{ field: "cliente", type: "textarea", required: true, label_es: "Datos del cliente" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 5000,
    risk_level: "high",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "sync",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 20 segundos",
    estimated_time_en: "≈ 20 seconds",
  },
  {
    task_id: "consent_registry_audit",
    display_name_es: "Auditoría de consentimientos",
    display_name_en: "Consent registry audit",
    description_es: "Trazabilidad y bases legales del tratamiento",
    description_en: "Traceability and legal bases",
    section_es: "Compliance",
    section_en: "Compliance",
    icon_hint: "clipboard-list",
    agent_chain: ["validador_amlkyc"],
    default_practice_area_tags: ["compliance"],
    required_inputs: [{ field: "registry_notes", type: "textarea", required: true, label_es: "Notas del registro" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 8000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 40 segundos",
    estimated_time_en: "≈ 40 seconds",
  },
  {
    task_id: "policy_gap_analysis",
    display_name_es: "Brechas de políticas internas",
    display_name_en: "Policy gap analysis",
    description_es: "Comparación frente a marco regulatorio RD",
    description_en: "Compare against RD regulatory frame",
    section_es: "Compliance",
    section_en: "Compliance",
    icon_hint: "scale",
    agent_chain: ["agente_opinion_legal"],
    default_practice_area_tags: ["compliance", "mercantil"],
    required_inputs: [{ field: "policy_text", type: "textarea", required: true, label_es: "Política o extracto" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 10000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_2_semistructured",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 2 minutos",
    estimated_time_en: "≈ 2 minutes",
  },
  {
    task_id: "jurisprudence_search",
    display_name_es: "Investigación de jurisprudencia",
    display_name_en: "Jurisprudence research",
    description_es: "Memorando con fuentes y advertencias de uso",
    description_en: "Memo with sources and usage warnings",
    section_es: "Investigación",
    section_en: "Research",
    icon_hint: "search",
    agent_chain: ["chat_asesor_legal"],
    default_practice_area_tags: ["civil", "procesal"],
    required_inputs: [{ field: "consulta", type: "textarea", required: true, label_es: "Consulta" }],
    output_type: "modal",
    requires_attorney_review: true,
    max_execution_time_ms: 12000,
    risk_level: "low",
    audit_required: true,
    min_knowledge_pack_level: "level_1_verified",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do"],
    estimated_time_es: "≈ 1 minuto",
    estimated_time_en: "≈ 1 minute",
  },
  {
    task_id: "cross_border_memo",
    display_name_es: "Memorando transfronterizo",
    display_name_en: "Cross-border memo",
    description_es: "Comparativo DO vs otros mercados (orientativo)",
    description_en: "DO vs other markets (orientative)",
    section_es: "Investigación",
    section_en: "Research",
    icon_hint: "globe",
    agent_chain: ["agente_opinion_legal"],
    default_practice_area_tags: ["mercantil"],
    required_inputs: [{ field: "consulta", type: "textarea", required: true, label_es: "Tema y jurisdicciones" }],
    output_type: "navigate",
    navigate_path: "/legal/research?task=cross_border_memo",
    requires_attorney_review: true,
    max_execution_time_ms: 15000,
    risk_level: "medium",
    audit_required: true,
    min_knowledge_pack_level: "level_2_semistructured",
    fallback_action: "review",
    sync_mode: "deep_async",
    tenant_features_required: [],
    compliance_jurisdiction_scope: ["do", "co", "mx"],
    estimated_time_es: "≈ 3 minutos",
    estimated_time_en: "≈ 3 minutes",
  },
];
