/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/autos/tenants/{tenant_id}/dealers/{dealer_id}/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Vehicle
         * @description Create a new vehicle listing.
         */
        post: operations["create_vehicle_api_v1_autos_tenants__tenant_id__dealers__dealer_id__vehicles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/vehicles/{vehicle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vehicle
         * @description Get a vehicle listing by ID (public, RLS public_read policy).
         */
        get: operations["get_vehicle_api_v1_autos_vehicles__vehicle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/vehicles/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Vehicles
         * @description Search vehicle listings (public marketplace browsing).
         */
        post: operations["search_vehicles_api_v1_autos_vehicles_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/vehicles/search/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Search Facets
         * @description Get faceted counts for search filters.
         */
        get: operations["get_search_facets_api_v1_autos_vehicles_search_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/vin/{vin}/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decode Vin
         * @description Decode a VIN using NHTSA vPIC API.
         */
        get: operations["decode_vin_api_v1_autos_vin__vin__decode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/tenants/{tenant_id}/dealers/{dealer_id}/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Leads
         * @description List leads for a dealer with pagination.
         */
        get: operations["list_leads_api_v1_autos_tenants__tenant_id__dealers__dealer_id__leads_get"];
        put?: never;
        /**
         * Create Lead
         * @description Create a new lead (buyer inquiry).
         */
        post: operations["create_lead_api_v1_autos_tenants__tenant_id__dealers__dealer_id__leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/tenants/{tenant_id}/leads/{lead_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Transition Lead
         * @description Transition a lead to a new status.
         */
        patch: operations["transition_lead_api_v1_autos_tenants__tenant_id__leads__lead_id__status_patch"];
        trace?: never;
    };
    "/api/v1/autos/finance/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Payment
         * @description Forward calculation: vehicle price → monthly payment.
         */
        post: operations["calculate_payment_api_v1_autos_finance_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/finance/inverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Max Price
         * @description Inverse calculation: monthly budget → max affordable vehicle price.
         */
        post: operations["calculate_max_price_api_v1_autos_finance_inverse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/finance/amortization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Amortization
         * @description Generate amortization table.
         */
        post: operations["get_amortization_api_v1_autos_finance_amortization_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/tenants/{tenant_id}/dealers/{dealer_id}/entitlements/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Entitlement
         * @description Check if a dealer is entitled to use a capability.
         */
        get: operations["check_entitlement_api_v1_autos_tenants__tenant_id__dealers__dealer_id__entitlements__capability__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description List available dealer subscription plans with ITBIS breakdown.
         */
        get: operations["list_plans_api_v1_autos_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/resolve/{hostname}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve Hostname
         * @description Resolve a hostname to a tenant_id (public, no auth required).
         */
        get: operations["resolve_hostname_api_v1_autos_resolve__hostname__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/tenants/{tenant_id}/dealers/{dealer_id}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Dealer Verification
         * @description Update dealer verification status (platform admin or tenant admin).
         */
        patch: operations["update_dealer_verification_api_v1_autos_admin_tenants__tenant_id__dealers__dealer_id__verification_patch"];
        trace?: never;
    };
    "/api/v1/autos/admin/tenants/{tenant_id}/vehicles/{vehicle_id}/moderation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Moderate Vehicle Listing
         * @description Moderate a vehicle listing (approve/reject/flag).
         */
        patch: operations["moderate_vehicle_listing_api_v1_autos_admin_tenants__tenant_id__vehicles__vehicle_id__moderation_patch"];
        trace?: never;
    };
    "/api/v1/autos/admin/tenants/{tenant_id}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Feature Flags
         * @description List all autos-portal feature flags for a tenant.
         */
        get: operations["list_feature_flags_api_v1_autos_admin_tenants__tenant_id__flags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/tenants/{tenant_id}/flags/{flag_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Feature Flag
         * @description Set a feature flag value. Critical flags require twofa_confirmed=true.
         */
        put: operations["set_feature_flag_api_v1_autos_admin_tenants__tenant_id__flags__flag_key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/impersonate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Impersonation Session
         * @description Start a controlled impersonation session (platform admin only).
         *
         *     Emits audit event. Maximum 2 hours. Destructive operations blocked.
         */
        post: operations["start_impersonation_session_api_v1_autos_admin_impersonate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/impersonate/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End Impersonation Session
         * @description End an impersonation session.
         */
        delete: operations["end_impersonation_session_api_v1_autos_admin_impersonate__token_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/kill-switch/{feature}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Kill Switch Endpoint
         * @description Activate a kill switch (platform admin only).
         */
        post: operations["activate_kill_switch_endpoint_api_v1_autos_admin_kill_switch__feature__post"];
        /**
         * Deactivate Kill Switch Endpoint
         * @description Deactivate a kill switch (platform admin only).
         */
        delete: operations["deactivate_kill_switch_endpoint_api_v1_autos_admin_kill_switch__feature__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/kill-switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Kill Switches Endpoint
         * @description List all kill switch states.
         */
        get: operations["list_kill_switches_endpoint_api_v1_autos_admin_kill_switches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/tenants/{tenant_id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tenant Usage
         * @description Get usage summary for a tenant.
         */
        get: operations["get_tenant_usage_api_v1_autos_admin_tenants__tenant_id__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/autos/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Audit Events
         * @description Search audit events (platform admin only).
         */
        get: operations["search_audit_events_api_v1_autos_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DealerVerifyRequest */
        DealerVerifyRequest: {
            /**
             * New Status
             * @enum {string}
             */
            new_status: "pending" | "verified" | "rejected" | "suspended";
            /** Reason */
            reason?: string | null;
        };
        /** FeatureFlagRequest */
        FeatureFlagRequest: {
            /** Enabled */
            enabled: boolean;
            /**
             * Twofa Confirmed
             * @default false
             */
            twofa_confirmed: boolean;
        };
        /** FinanceCalculateRequest */
        FinanceCalculateRequest: {
            /** Vehicle Price */
            vehicle_price: number;
            /** Down Payment */
            down_payment: number;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /** Term Months */
            term_months: number;
        };
        /** FinanceInverseRequest */
        FinanceInverseRequest: {
            /** Monthly Budget */
            monthly_budget: number;
            /** Down Payment */
            down_payment: number;
            /** Annual Rate Pct */
            annual_rate_pct: number;
            /** Term Months */
            term_months: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImpersonateRequest */
        ImpersonateRequest: {
            /** Target User Id */
            target_user_id: string;
            /** Target Tenant Id */
            target_tenant_id: string;
            /** Justification */
            justification: string;
            /**
             * Duration Hours
             * @default 1
             */
            duration_hours: number;
        };
        /** KillSwitchRequest */
        KillSwitchRequest: {
            /** Reason */
            reason: string;
        };
        /** LeadCreateRequest */
        LeadCreateRequest: {
            /** Vehicle Id */
            vehicle_id?: string | null;
            /** Buyer Name */
            buyer_name: string;
            /** Buyer Phone */
            buyer_phone?: string | null;
            /** Buyer Email */
            buyer_email?: string | null;
            /** Buyer Message */
            buyer_message?: string | null;
            /**
             * Source
             * @default marketplace
             * @enum {string}
             */
            source: "marketplace" | "referral" | "social" | "walk_in" | "phone" | "website" | "other";
            /**
             * Priority
             * @default normal
             * @enum {string}
             */
            priority: "low" | "normal" | "high" | "urgent";
            /**
             * Finance Interested
             * @default false
             */
            finance_interested: boolean;
            /** Monthly Budget Rd */
            monthly_budget_rd?: number | null;
        };
        /** LeadTransitionRequest */
        LeadTransitionRequest: {
            /**
             * New Status
             * @enum {string}
             */
            new_status: "new" | "contacted" | "qualified" | "negotiating" | "won" | "lost" | "archived";
            /** Actor */
            actor?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VehicleCreateRequest */
        VehicleCreateRequest: {
            /** Make */
            make: string;
            /** Model */
            model: string;
            /** Year */
            year: number;
            /** Vin */
            vin?: string | null;
            /** Legacy Vehicle Identifier */
            legacy_vehicle_identifier?: string | null;
            /** Trim */
            trim?: string | null;
            /** Body Type */
            body_type?: string | null;
            /** Fuel Type */
            fuel_type?: string | null;
            /** Transmission */
            transmission?: string | null;
            /** Drivetrain */
            drivetrain?: string | null;
            /** Exterior Color */
            exterior_color?: string | null;
            /** Interior Color */
            interior_color?: string | null;
            /** Mileage Km */
            mileage_km?: number | null;
            /**
             * Condition
             * @default used
             * @enum {string}
             */
            condition: "new" | "used";
            /** Price Rd */
            price_rd?: number | null;
            /** Price Usd */
            price_usd?: number | null;
            /** Description */
            description?: string | null;
            /** Province */
            province?: string | null;
            /** Municipality */
            municipality?: string | null;
        };
        /** VehicleModerateRequest */
        VehicleModerateRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "approved" | "rejected" | "flagged" | "pending_review";
            /** Reason */
            reason?: string | null;
        };
        /** VehicleSearchRequest */
        VehicleSearchRequest: {
            /** Query */
            query?: string | null;
            /** Make */
            make?: string | null;
            /** Model */
            model?: string | null;
            /** Year Min */
            year_min?: number | null;
            /** Year Max */
            year_max?: number | null;
            /** Price Min */
            price_min?: number | null;
            /** Price Max */
            price_max?: number | null;
            /** Condition */
            condition?: ("new" | "used") | null;
            /** Body Type */
            body_type?: string | null;
            /** Fuel Type */
            fuel_type?: string | null;
            /** Transmission */
            transmission?: string | null;
            /** Province */
            province?: string | null;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 20
             */
            page_size: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_vehicle_api_v1_autos_tenants__tenant_id__dealers__dealer_id__vehicles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                dealer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle_api_v1_autos_vehicles__vehicle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_vehicles_api_v1_autos_vehicles_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_facets_api_v1_autos_vehicles_search_facets_get: {
        parameters: {
            query?: {
                q?: string | null;
                /** @description Comma-separated facet names */
                facets?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decode_vin_api_v1_autos_vin__vin__decode_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vin: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_leads_api_v1_autos_tenants__tenant_id__dealers__dealer_id__leads_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
                dealer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_autos_tenants__tenant_id__dealers__dealer_id__leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                dealer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_lead_api_v1_autos_tenants__tenant_id__leads__lead_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_payment_api_v1_autos_finance_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinanceCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_max_price_api_v1_autos_finance_inverse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinanceInverseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_amortization_api_v1_autos_finance_amortization_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinanceCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_entitlement_api_v1_autos_tenants__tenant_id__dealers__dealer_id__entitlements__capability__get: {
        parameters: {
            query?: {
                quantity?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
                dealer_id: string;
                capability: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_autos_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resolve_hostname_api_v1_autos_resolve__hostname__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hostname: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_dealer_verification_api_v1_autos_admin_tenants__tenant_id__dealers__dealer_id__verification_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                dealer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealerVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    moderate_vehicle_listing_api_v1_autos_admin_tenants__tenant_id__vehicles__vehicle_id__moderation_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleModerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feature_flags_api_v1_autos_admin_tenants__tenant_id__flags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_feature_flag_api_v1_autos_admin_tenants__tenant_id__flags__flag_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                flag_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureFlagRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_impersonation_session_api_v1_autos_admin_impersonate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpersonateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_impersonation_session_api_v1_autos_admin_impersonate__token_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_kill_switch_endpoint_api_v1_autos_admin_kill_switch__feature__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KillSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_kill_switch_endpoint_api_v1_autos_admin_kill_switch__feature__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_kill_switches_endpoint_api_v1_autos_admin_kill_switches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_tenant_usage_api_v1_autos_admin_tenants__tenant_id__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_audit_events_api_v1_autos_admin_audit_get: {
        parameters: {
            query?: {
                tenant_id?: string | null;
                event_type?: string | null;
                actor_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
