// config/cores.ts - All 20 cores configuration

import { Core } from '@/types';

export const CORES_CONFIG: Record<string, Omit<Core, 'agents'>> = {
  marketing: {
    id: 'marketing',
    name: 'marketing',
    displayName: 'Marketing Neural Suite',
    description: 'Agentes de marketing con IA para campañas, leads, segmentación y más',
    icon: '📢',
    color: '#FFD166',
    gradient: 'linear-gradient(135deg, #FFD166 0%, #00E5FF 50%, #A0F 100%)',
    agentCount: 33,
    status: 'active',
  },
  legal: {
    id: 'legal',
    name: 'legal',
    displayName: 'Legal AI System',
    description: 'Análisis de contratos, compliance legal y automatización jurídica',
    icon: '⚖️',
    color: '#C77DFF',
    gradient: 'linear-gradient(135deg, #C77DFF 0%, #7CF 50%, #FF0 100%)',
    agentCount: 32,
    status: 'active',
  },
  logistica: {
    id: 'logistica',
    name: 'logistica',
    displayName: 'Logística Inteligente',
    description: 'Optimización de rutas, inventario y cadena de suministro',
    icon: '🚚',
    color: '#7CFFB2',
    gradient: 'linear-gradient(135deg, #7CFFB2 0%, #00C2A8 50%, #00E5FF 100%)',
    agentCount: 23,
    status: 'active',
  },
  contabilidad: {
    id: 'contabilidad',
    name: 'contabilidad',
    displayName: 'Contabilidad Cuántica',
    description: 'Reconciliación automática, IFRS compliance y reportes financieros',
    icon: '📊',
    color: '#00E5FF',
    gradient: 'linear-gradient(135deg, #00E5FF 0%, #A0F 50%, #FF0 100%)',
    agentCount: 22,
    status: 'active',
  },
  presupuesto: {
    id: 'presupuesto',
    name: 'presupuesto',
    displayName: 'Presupuesto Inteligente',
    description: 'Forecasting ML, budget optimization y análisis financiero',
    icon: '💰',
    color: '#00E5FF',
    gradient: 'linear-gradient(135deg, #00E5FF 0%, #7CFFB2 50%, #FFD166 100%)',
    agentCount: 13,
    status: 'active',
  },
  originacion: {
    id: 'originacion',
    name: 'originacion',
    displayName: 'Originación Neural',
    description: 'Proceso de originación de créditos con IA',
    icon: '🌱',
    color: '#00E5FF',
    gradient: 'linear-gradient(135deg, #00E5FF 0%, #A0F 30%, #FF0 100%)',
    agentCount: 10,
    status: 'active',
  },
  rrhh: {
    id: 'rrhh',
    name: 'rrhh',
    displayName: 'Recursos Humanos IA',
    description: 'Talent acquisition, performance analytics y gestión de personal',
    icon: '👥',
    color: '#FFD166',
    gradient: 'linear-gradient(135deg, #FFD166 0%, #FF3D71 50%, #C77DFF 100%)',
    agentCount: 10,
    status: 'active',
  },
  educacion: {
    id: 'educacion',
    name: 'educacion',
    displayName: 'Educación Adaptativa',
    description: 'Learning paths personalizados y skill assessment',
    icon: '🎓',
    color: '#7CFFB2',
    gradient: 'linear-gradient(135deg, #7CFFB2 0%, #00E5FF 50%, #C77DFF 100%)',
    agentCount: 9,
    status: 'active',
  },
  investigacion: {
    id: 'investigacion',
    name: 'investigacion',
    displayName: 'Investigación I+D',
    description: 'Data mining, innovation tracking y research automation',
    icon: '🔬',
    color: '#C77DFF',
    gradient: 'linear-gradient(135deg, #C77DFF 0%, #00E5FF 50%, #7CFFB2 100%)',
    agentCount: 9,
    status: 'active',
  },
  ventascrm: {
    id: 'ventascrm',
    name: 'ventascrm',
    displayName: 'Ventas & CRM Cuántico',
    description: 'Lead scoring, pipeline automation y gestión de ventas',
    icon: '🤝',
    color: '#FFD166',
    gradient: 'linear-gradient(135deg, #FFD166 0%, #FF3D71 50%, #00E5FF 100%)',
    agentCount: 9,
    status: 'active',
  },
  regtech: {
    id: 'regtech',
    name: 'regtech',
    displayName: 'RegTech Compliance',
    description: 'AML/KYC automation y regulatory reporting',
    icon: '🛡️',
    color: '#C77DFF',
    gradient: 'linear-gradient(135deg, #C77DFF 0%, #FF3D71 50%, #FFD166 100%)',
    agentCount: 8,
    status: 'active',
  },
  compliance: {
    id: 'compliance',
    name: 'compliance',
    displayName: 'Compliance Core',
    description: 'Verificación de cumplimiento normativo',
    icon: '✅',
    color: '#7CFFB2',
    gradient: 'linear-gradient(135deg, #7CFFB2 0%, #00E5FF 50%, #C77DFF 100%)',
    agentCount: 5,
    status: 'active',
  },
  decision: {
    id: 'decision',
    name: 'decision',
    displayName: 'Motor de Decisiones',
    description: 'ML avanzado para scoring dinámico y decisiones automáticas',
    icon: '🎯',
    color: '#FF3D71',
    gradient: 'linear-gradient(135deg, #FF3D71 0%, #FF00FF 50%, #FFD166 100%)',
    agentCount: 5,
    status: 'active',
  },
  experiencia: {
    id: 'experiencia',
    name: 'experiencia',
    displayName: 'Experiencia Cliente',
    description: 'Personalización y journey mapping del cliente',
    icon: '😊',
    color: '#FFD166',
    gradient: 'linear-gradient(135deg, #FFD166 0%, #7CFFB2 50%, #00E5FF 100%)',
    agentCount: 5,
    status: 'active',
  },
  fortaleza: {
    id: 'fortaleza',
    name: 'fortaleza',
    displayName: 'Fortaleza Security',
    description: 'Threat detection y cyber defense',
    icon: '🏰',
    color: '#FF3D71',
    gradient: 'linear-gradient(135deg, #FF3D71 0%, #C77DFF 50%, #00E5FF 100%)',
    agentCount: 5,
    status: 'active',
  },
  inteligencia: {
    id: 'inteligencia',
    name: 'inteligencia',
    displayName: 'Inteligencia Neural',
    description: 'Business intelligence y predictive analytics',
    icon: '🧠',
    color: '#00E5FF',
    gradient: 'linear-gradient(135deg, #00E5FF 0%, #C77DFF 50%, #FF3D71 100%)',
    agentCount: 5,
    status: 'active',
  },
  operacional: {
    id: 'operacional',
    name: 'operacional',
    displayName: 'Operaciones Automáticas',
    description: 'Workflow optimization y RPA avanzado',
    icon: '⚙️',
    color: '#7CFFB2',
    gradient: 'linear-gradient(135deg, #7CFFB2 0%, #00E5FF 50%, #FFD166 100%)',
    agentCount: 5,
    status: 'active',
  },
  orchestration: {
    id: 'orchestration',
    name: 'orchestration',
    displayName: 'Orchestration Center',
    description: 'Workflow engine y API management',
    icon: '🎛️',
    color: '#C77DFF',
    gradient: 'linear-gradient(135deg, #C77DFF 0%, #00E5FF 50%, #7CFFB2 100%)',
    agentCount: 5,
    status: 'active',
  },
  recuperacion: {
    id: 'recuperacion',
    name: 'recuperacion',
    displayName: 'Recuperación IA',
    description: 'Estrategias de cobranza personalizadas',
    icon: '💳',
    color: '#FF3D71',
    gradient: 'linear-gradient(135deg, #FF3D71 0%, #FFD166 50%, #7CFFB2 100%)',
    agentCount: 5,
    status: 'active',
  },
  vigilancia: {
    id: 'vigilancia',
    name: 'vigilancia',
    displayName: 'Vigilancia Continua',
    description: 'Detección de fraude y alertas en tiempo real',
    icon: '👁️',
    color: '#FF3D71',
    gradient: 'linear-gradient(135deg, #FF3D71 0%, #C77DFF 50%, #00E5FF 100%)',
    agentCount: 4,
    status: 'active',
  },
};

// Group cores by category for sidebar
export const CORE_CATEGORIES = {
  financial: {
    name: '🧠 CORE FINANCIERO',
    cores: ['originacion', 'recuperacion', 'contabilidad', 'presupuesto'],
  },
  risk: {
    name: '⚠️ CORE DE RIESGOS',
    cores: ['decision', 'vigilancia', 'compliance'],
  },
  operations: {
    name: '⚙️ CORE OPERACIONAL',
    cores: ['operacional', 'rrhh', 'logistica', 'investigacion', 'inteligencia', 'orchestration'],
  },
  customer: {
    name: '👥 CORE CLIENTE',
    cores: ['experiencia', 'marketing', 'ventascrm', 'educacion'],
  },
  regtech: {
    name: '🛡️ CORE REGTECH',
    cores: ['legal', 'regtech', 'fortaleza'],
  },
};

export const getAllCores = () => Object.values(CORES_CONFIG);
export const getCoreById = (id: string) => CORES_CONFIG[id];
export const getTotalAgents = () => getAllCores().reduce((sum, core) => sum + core.agentCount, 0);
