import { computeWizardCompleteness } from "@/lib/credit-hub/dealer/wizard-completeness";
import type { ApplicationFormData } from "@/components/credit-hub/dealer/wizard/WizardContainer";
import { DEFAULT_DO_REQUIRED_DOCUMENTS } from "@/lib/credit-hub/defaults/do-required-documents";

const minimalT = {
  validation: {
    invalid_cedula: "",
    invalid_passport: "",
    age_min: () => "",
    relationship_other_required: "",
    guarantor_income_positive: "",
    cedula_match_applicant: "",
  },
} as const;

const emptyForm: ApplicationFormData = {
  applicant_full_name: "Ana",
  applicant_identification: "00112345678",
  applicant_date_of_birth: "1990-01-01",
  applicant_marital_status: "soltero",
  applicant_phone: "8095550000",
  applicant_email: "a@test.com",
  applicant_address: "Calle 1",
  applicant_city: "SD",
  applicant_province: "DN",
  applicant_country: "DO",
  applicant_document_type: "CEDULA",
  applicant_document_other_type: "",
  applicant_age: "36",
  employment_type: "asalariado",
  employer_name: "ACME",
  employment_position: "Analista",
  employment_start_date: "2020-01-01",
  employer_address: "Zona",
  employer_province: "DN",
  employer_city: "SD",
  contract_type: "indefinido",
  monthly_income: "50000",
  has_other_income: "no",
  other_incomes: [],
  work_phone: "8095550001",
  requested_amount: "400000",
  desired_term: "60",
  down_payment: "50000",
  monthly_debts: "0",
  estimated_monthly_expenses: "0",
  bank_institution: "",
  has_bank_account: "yes",
  has_late_payment_history: "no",
  max_late_payment_days: "",
  product_type: "Auto",
  vehicle_brand_other: "",
  vehicle_version: "",
  vehicle_color: "",
  vehicle_mileage: "",
  vehicle_make: "Toyota",
  vehicle_model: "Corolla",
  vehicle_year: "2024",
  vehicle_price: "450000",
  dealer_supplier: "Dealer",
  vehicle_condition: "new",
  co_debtor_required: "no",
  co_debtor_document_type: "CEDULA",
  co_debtor_document_other_type: "",
  co_debtor_date_of_birth: "",
  co_debtor_email: "",
  co_debtor_address: "",
  co_debtor_province: "",
  co_debtor_city: "",
  co_debtor_employer_name: "",
  co_debtor_employment_start_date: "",
  co_debtor_relationship_other: "",
  co_debtor_full_name: "",
  co_debtor_identification: "",
  co_debtor_phone: "",
  co_debtor_monthly_income: "",
  co_debtor_relationship: "",
  co_debtor_employment: "",
  documents_received: { cedula: true },
  document_notes: {},
  additional_document_items: [],
  consent_presence: "present",
  consent_bureau_authorization: false,
  consent_terms_accepted: false,
  consent_data_processing_authorization: false,
  consent_signature_full_name: "",
  consent_present_confirmed: false,
  consent_method: "",
  consent_audit_hash: "",
  consent_accepted_at: "",
  consent_sms_otp_sent: false,
  consent_dealer_otp_code: "",
  segment_zone: "",
  segment_vehicle_type: "",
};

describe("wizard-completeness", () => {
  test("returns higher score when more fields filled", () => {
    const config = {
      min_age: 18,
      max_age: 75,
      garante_required: false,
      default_document_type: "CEDULA",
      required_documents: DEFAULT_DO_REQUIRED_DOCUMENTS,
      consent_application_id_ready: false,
    };
    const low = computeWizardCompleteness(
      { ...emptyForm, applicant_full_name: "" },
      config,
      minimalT as never,
    );
    const mid = computeWizardCompleteness(emptyForm, config, minimalT as never);
    expect(mid).toBeGreaterThan(low);
  });
});
