/** Nauta v2 microcopy — BEHAVIOR_SPEC §9. Do not invent UI text outside this module. */

export const S = {
  brand: {
    name: "Nauta",
    subtitle: "Nómina Digital",
  },
  nav: {
    operacion: "Operación",
    piso: "Piso de operaciones",
    tablero: "Tablero",
    expedientes: "Expedientes",
    super: "Centro de supervisión",
    admin: "Administración",
    planes: "Nómina y planes",
    evidencia: "Evidencia y auditoría",
    config: "Configuración",
  },
  rail: {
    tenantLabel: "Institución · white-label",
    userName: "Ramón Almonte",
    userRole: "Gerente de Cumplimiento",
  },
  header: {
    searchPlaceholder: "Buscar empleado, tarea o expediente…",
    clockPrefix: "Laboratorio en vivo ·",
    clockSuffix: "AST",
  },
  views: {
    piso: "Piso de operaciones",
    tablero: "Tablero",
    expedienteE1: "Expediente · E1 Verificador KYC",
    expedienteE2: "Expediente · E2 Analista de Listas 155-17",
    expedienteE16: "Expediente · E16 Operador de Tareas Libres",
    super: "Centro de supervisión",
  },
  taskComposer: {
    label: "Asignar tarea",
    placeholder: "Describe la tarea en tus palabras…",
    counter: (n: number, max: number) => `${n} / ${max}`,
    selectForLive: "Usar en ejecución live",
    selectedForLive: "Seleccionado para ejecución live",
  },
  live: {
    pendingApproval: "Esperando aprobación del supervisor",
    pendingApprovalLink: "Centro de supervisión",
    deliverablesTitle: "Entregables",
    recording: "Grabación",
    screenshot: "Captura final",
    output: "Resultado",
    lastStepSummary: "Resumen del último paso",
  },
  report: {
    summaryTitle: "Resumen del run",
    agentTitle: "Reporte del agente",
    taskAssigned: "Tarea asignada",
    instruction: "Instrucción",
    status: "Estado",
    statusCompleted: "Completado",
    statusFailed: "Falló",
    duration: "Duración",
    stepCount: "Pasos ejecutados",
    cost: "Costo estimado",
    tokens: "Tokens",
    findings: "Hallazgos",
    engine: "Motor",
    runId: "Run ID",
    timestamp: "Finalizado",
    copyReport: "Copiar reporte",
    copied: "Copiado",
    copyFailed: "No se pudo copiar",
    downloadReport: "Descargar reporte",
    openRecording: "Abrir grabación",
    outputMissing: "Sin output en la respuesta del servidor.",
    iframeEnded: "Sesión del navegador finalizada. Mostrando reporte del agente.",
    gapTitle: "GAP BACKEND — campos ausentes en GET /api/v1/nauta/runs/{id}:",
  },
  kpi: {
    hoursSaved: "Horas ahorradas · mes",
    juniorAnalysts: (n: number) => `≈ ${n} analistas junior`,
    successRate: "Tasa de éxito",
    successDelta: "▲ 0.3 pp objetivo ≥ 98%",
    runsMonth: "Ejecuciones · mes",
    runsDelta: "▲ 12.4% vs. mes previo",
    payrollCost: "Costo de nómina · mes",
    payrollPerEmployee: (amount: string) => `${amount} por empleado`,
    pendingApprovals: "Aprobaciones pendientes",
    pendingHint: "requieren su autorización",
  },
  toolbar: {
    employees16: "Los 16 empleados",
    byLifecycle: "Empleados por ciclo de vida",
    plans: "Nómina por departamento",
  },
  seg: {
    byDept: "◧ Por departamento",
    byStatus: "◔ Por estado",
    asPlans: "₽ Ver como planes",
  },
  dept: {
    d0: "Plataforma",
    d1: "Cumplimiento",
    d2: "Crédito",
    d3: "Legal",
    d4: "Operaciones",
    d5: "Marketing",
    d1Sub: "4 empleados · incluye el rol estrella",
    oneEmployee: "1 empleado",
    nEmployees: (n: number) => `${n} empleados`,
  },
  statusGroup: {
    prioridad: "Prioridad de diseño",
    prioridadSub: "rol estrella",
    listo: "Listo",
    listoSub: "lab-ready · contratable",
    laboratorio: "Laboratorio",
    laboratorioSub: "en pruebas",
    concepto: "Concepto",
    conceptoSub: "acceso anticipado",
  },
  employee: {
    riskLabel: "Riesgo de tarea",
    supervisorLabel: "Supervisor",
    starTag: "◆ Rol estrella",
    liveE1: "Corriendo en laboratorio ahora",
    liveE2: "Rol estrella · en diseño prioritario",
    pill: {
      prioridad: "Prioridad de diseño",
      listo: "Listo",
      laboratorio: "Laboratorio",
      concepto: "Concepto",
      enTurno: "En turno",
      activo: "Activo",
    },
    risk: {
      bajo: "Bajo",
      medio: "Medio",
      alto: "Alto",
      critico: "Crítico",
    },
    cta: {
      contratar: "Contratar",
      reservar: "Reservar acceso anticipado",
      verPrueba: "Ver resultados de prueba",
    },
  },
  activity: {
    title: "Actividad del laboratorio",
    collapse: "▾",
    expand: "▸",
  },
  feed: {
    metaSealed: "hace 4 s · evidencia sellada",
    meta22s: "hace 22 s",
    metaApproval: "hace 1 min · requiere aprobación",
    metaHash: "hace 6 min · SHA-256 · 0x8f3a…c21",
    meta12m: "hace 12 min",
    meta15m: "hace 15 min",
    e2Clean: "E2 · Listas restrictivas completó cribado Ley 155-17 sin coincidencias",
    e1Kyc: "E1 · KYC validó cédula y prueba de vida en laboratorio",
    e2Partial: "E2 · Listas derivó coincidencia parcial a autorización humana",
    e0Seal: "E0 · Auditor de plataforma selló el paquete de evidencia diario",
    e9Process: "E9 · Monitor procesal detectó nuevo proceso en cartera (prueba piloto)",
    e1Close: "E1 · KYC cerró expediente en 3.1 s",
  },
  tablero: {
    liveTitle: "Actividad en vivo",
    liveSub: "laboratorio · piloto",
    realtime: "tiempo real",
    loadTitle: "Carga por departamento",
    loadSub: "ejecuciones · hoy",
    returnTitle: "Retorno del mes",
    humanCost: "costo equivalente humano",
    vs: "vs.",
    digitalPayroll: "nómina digital Nauta",
    savebar: (savings: string, hours: string) =>
      `◱ Ahorro neto del mes: ${savings} · ${hours} horas devueltas al equipo`,
  },
  expedienteE1: {
    title: "Verificador KYC Público RD",
    code: "E1 · Departamento de Cumplimiento (D1)",
    tagListo: "Listo · lab-ready",
    tagRisk: "Riesgo alto",
    tagSupervisor: (name: string) => `Supervisado por ${name}`,
    metaRegistered: "Registrado",
    metaRegisteredVal: "14 mar 2024",
    metaSchedule: "Horario objetivo",
    metaScheduleVal: "L–S · 06:00–20:00",
    metaCost: "Costo mensual",
    metaCostVal: "RD$ 14,200",
    profileTitle: "Perfil del rol",
    profileBody:
      "Recibe cada solicitud de apertura y verifica la identidad del cliente de extremo a extremo: coteja la cédula contra fuentes públicas de RD, ejecuta prueba de vida, valida el domicilio y arma el expediente digital. Cada decisión queda sellada con su evidencia. Cuando detecta un documento alterado o un dato que no cuadra, no decide solo: eleva el caso a un analista humano con toda la traza.",
    marco: "Marco regulatorio",
    marcoVal: "Ley 155-17 · Circular SB",
    integraciones: "Integraciones",
    integracionesVal: "Fuentes públicas RD · biometría",
    umbral: "Umbral de autorización",
    umbralVal: "Documento dudoso → humano",
    historyTitle: "Historial de ejecuciones",
    historySub: "laboratorio · últimas 24 h",
    perfTitle: "Desempeño en laboratorio",
    perfVerifications: "Verificaciones",
    perfSuccess: "Tasa de éxito",
    perfEscalated: "Elevadas a humano",
    perfAvgTime: "Tiempo medio",
    costTitle: "Costo vs. horas humanas",
    costHuman: "trabajo humano ahorrado / mes",
    costEmployee: "costo del empleado",
    costSavebar: "◱ Equivale a ~1.3 analistas junior (RD$ 35–55K c/u) a una fracción del costo",
    evidenceTitle: "Evidencia · sellos de auditoría",
    evidenceSub: "SHA-256",
    liveTitle: "Ver trabajar en vivo",
    liveHeading: "Transmisión disponible próximamente",
    liveBody:
      "Observe al empleado ejecutar cada paso en tiempo real, con la evidencia generándose sello a sello.",
  },
  expedienteE2: {
    title: "Analista de Listas Restrictivas",
    code: "E2 · Departamento de Cumplimiento (D1) · Ley 155-17",
    tagStar: "◆ Rol estrella",
    tagPrioridad: "Prioridad de diseño",
    tagRisk: "Riesgo crítico",
    tagSupervisor: (name: string) => `Supervisado por ${name}`,
    metaLists: "Listas",
    metaListsVal: "OFAC · ONU · locales RD",
    metaMarco: "Marco",
    metaMarcoVal: "Ley 155-17 · Circular SB",
    metaCost: "Costo mensual",
    metaCostVal: "RD$ 16,800",
    profileTitle: "Perfil del rol",
    profileSub: "obligación legal",
    callout:
      "Cribado contra OFAC, ONU y listas locales conforme a la Ley 155-17 — la tarea que la Superintendencia audita.",
    profileBody:
      "Coteja cada cliente nuevo y cada relación existente contra las listas restrictivas actualizadas. Una coincidencia exacta bloquea la apertura de forma automática; una coincidencia parcial no se decide sola: activa el candado de supervisión y eleva el caso a un oficial humano con toda la evidencia.",
    freq: "Frecuencia",
    freqVal: "Cada alta + barridos periódicos",
    sources: "Fuentes de listas",
    sourcesVal: "OFAC (SDN) · ONU · locales RD",
    umbral: "Umbral de autorización",
    umbralVal: "Coincidencia ≥ umbral → humano",
    evidenceMeta: "Evidencia",
    evidenceMetaVal: "Un sello por cada cribado",
    historyTitle: "Historial de ejecuciones",
    historySub: "el caso que importa",
    heroMetric: "0",
    heroLabel: "coincidencias sin revisar",
    heroSub: "en 34,812 cribados este mes · 100% con evidencia sellada",
    perfTitle: "Desempeño en laboratorio",
    perfScreenings: "Cribados · mes",
    perfMatches: "Coincidencias detectadas",
    perfEscalated: "Elevadas a humano",
    perfUnreviewed: "Sin revisar",
    costTitle: "Costo vs. riesgo regulatorio",
    costEmployee: "costo del empleado / mes",
    costVs: "frente a",
    costSanction: "Hallazgo SB\n155-17",
    costSanctionSub: "sanción · riesgo material",
    riskbar:
      "▲ Un solo cliente sancionable sin cribar puede costar mucho más que años de este empleado — además del riesgo reputacional y para la licencia bancaria.",
    evidenceTitle: "Evidencia · sellos de auditoría",
    liveTitle: "Ver trabajar en vivo",
    liveHeading: "Transmisión disponible próximamente",
    liveBody:
      "Observe el cribado contra OFAC, ONU y listas locales en tiempo real, con cada coincidencia sellada al instante.",
    lockchip: "◈ Candado de supervisión · derivado a Lic. C. Disla",
  },
  expedienteE16: {
    title: "Operador de Tareas Libres",
    code: "E16 · Departamento de Operaciones (D4)",
    tagListo: "Listo · instrucciones libres",
    tagSupervisor: (name: string) => `Supervisado por ${name}`,
    profileTitle: "Perfil del rol",
    profileBody:
      "Recibe instrucciones en lenguaje natural y las ejecuta en el navegador con evidencia sellada. Ideal para tareas ad hoc que no encajan en una plantilla fija.",
    liveTitle: "Ver trabajar en vivo",
  },
  super: {
    bannerTitle: "El humano siempre tiene la última palabra",
    bannerBody:
      "Ninguna tarea de alto riesgo se ejecuta sin su autorización. Cada decisión queda registrada a su nombre, con evidencia sellada.",
    pendingLabel: "pendientes de autorización",
    queueTitle: "Cola de aprobaciones",
    queueSub: "ordenadas por riesgo",
    colTask: "Tarea",
    colEmployee: "Empleado",
    colEvidence: "Evidencia",
    colDecision: "Decisión",
    btnReview: "Revisar",
    btnReject: "Rechazar",
    btnApprove: "✓ Autorizar",
    emptyTitle: "Todo autorizado. Sus empleados están al día.",
    emptyBody:
      "No hay tareas de alto riesgo esperando su decisión. La cola se sella y vuelve a abrirse cuando un empleado eleve un caso.",
    emptyStamp: "Última autorización sellada · hoy",
  },
  bundle: {
    starTag: "◆ Incluye el rol estrella",
    deptPrefix: (code: string) => `Departamento ${code}`,
    perMonth: "/ mes",
    nDigital: (n: number) => (n === 1 ? "1 empleado digital" : `${n} empleados digitales`),
    hireDept: "Contratar departamento",
    d1Vs: "Menos que un solo hallazgo 155-17 de la Superintendencia — se ancla contra la sanción, no contra el salario.",
    normalVs: "vs. 1 analista junior: RD$ 35–55K/mes + cargas.",
    e2Value: "Cribado Ley 155-17 — gasto obligatorio, riesgo material",
  },
  seal: {
    verified: "✓ Verificado",
    immutable: (time: string) => `Emitido ${time} AST · inmutable`,
  },
} as const;

export const DEPT_LABELS: Record<string, string> = {
  d0: "D0 Plataforma",
  d1: "D1 Cumplimiento",
  d2: "D2 Crédito",
  d3: "D3 Legal",
  d4: "D4 Operaciones",
  d5: "D5 Marketing",
};

export const DEPT_NAMES: Record<string, string> = {
  d0: S.dept.d0,
  d1: S.dept.d1,
  d2: S.dept.d2,
  d3: S.dept.d3,
  d4: S.dept.d4,
  d5: S.dept.d5,
};

export const ROLE_NAMES: Record<string, string> = {
  E0: "Auditor Digital de Plataforma",
  E1: "Verificador KYC Público RD",
  E2: "Analista de Listas Restrictivas (Ley 155-17)",
  E3: "Monitor Regulatorio SB/DGII",
  E4: "Gestor de Re-verificación Periódica KYC",
  E5: "Analista de Completitud Documental",
  E6: "Operador de Estado Dealer-Bank",
  E7: "Verificador de Garantías Vehiculares",
  E8: "Analista de Consistencia de Fraude Documental",
  E9: "Monitor Procesal y de Expedientes",
  E10: "Gestor de Vencimientos y Renovaciones",
  E11: "Preparador de Expediente Guiado",
  E12: "Conciliador Contable/Operativo",
  E13: "Triage de Inbox Operativo",
  E14: "Preparador de Reportería Regulatoria",
  E15: "Monitor de Reputación y Cumplimiento Publicitario",
  E16: "Operador de Tareas Libres",
};

export const SUPERVISORS: Record<string, string> = {
  d0: "Plataforma Nadakki",
  d1: "Lic. C. Disla",
  d2: "Ing. M. Reyes",
  d3: "Lic. P. Núñez",
  d4: "Lic. J. Fermín",
  d5: "Lic. A. Peralta",
};
